// NOTE: Taken (almost) verbatim from https://github.com/kamiyaa/joshuto
// License GNU Lesser General Public License v3.0

//use phf::phf_map;

use std::collections::HashMap;
use lazy_static::lazy_static;

pub const DEFAULT_DIR: &str = "";
pub const DEFAULT_FILE: &str = "";

// all those glyphs will show as weird squares if you don't have the correct patched font
// My advice is to use NerdFonts which can be found here:
// https://github.com/ryanoasis/nerd-fonts
//pub static FILE_NODE_EXTENSIONS: phf::Map<&'static str, &'static str> = phf_map! {
lazy_static! {
  pub static ref FILE_NODE_EXTENSIONS: HashMap<&'static str, &'static str> =  { 
    [
    ("7z"       , ""),
    ("a"        , ""),
    ("ai"       , ""),
    ("apk"      , ""),
    ("asm"      , ""),
    ("asp"      , ""),
    ("aup"      , ""),
    ("avi"      , ""),
    ("awk"      , ""),
    ("bash"     , ""),
    ("bat"      , ""),
    ("bmp"      , ""),
    ("bz2"      , ""),
    ("c"        , ""),
    ("c++"      , ""),
    ("cab"      , ""),
    ("cbr"      , ""),
    ("cbz"      , ""),
    ("cc"       , ""),
    ("class"    , ""),
    ("clj"      , ""),
    ("cljc"     , ""),
    ("cljs"     , ""),
    ("cmake"    , ""),
    ("coffee"   , ""),
    ("conf"     , ""),
    ("cp"       , ""),
    ("cpio"     , ""),
    ("cpp"      , ""),
    ("cs"       , ""),
    ("csh"      , ""),
    ("css"      , ""),
    ("cue"      , ""),
    ("cvs"      , ""),
    ("cxx"      , ""),
    ("d"        , ""),
    ("dart"     , ""),
    ("db"       , ""),
    ("deb"      , ""),
    ("diff"     , ""),
    ("dll"      , ""),
    ("doc"      , ""),
    ("docx"     , ""),
    ("dump"     , ""),
    ("edn"      , ""),
    ("eex"      , ""),
    ("efi"      , ""),
    ("ejs"      , ""),
    ("elf"      , ""),
    ("elm"      , ""),
    ("epub"     , ""),
    ("erl"      , ""),
    ("ex"       , ""),
    ("exe"      , ""),
    ("exs"      , ""),
    ("f//"      , ""),
    ("fifo"     , "|"),
    ("fish"     , ""),
    ("flac"     , ""),
    ("flv"      , ""),
    ("fs"       , ""),
    ("fsi"      , ""),
    ("fsscript" , ""),
    ("fsx"      , ""),
    ("gem"      , ""),
    ("gemspec"  , ""),
    ("gif"      , ""),
    ("go"       , ""),
    ("gz"       , ""),
    ("gzip"     , ""),
    ("h"        , ""),
    ("haml"     , ""),
    ("hbs"      , ""),
    ("hh"       , ""),
    ("hpp"      , ""),
    ("hrl"      , ""),
    ("hs"       , ""),
    ("htaccess" , ""),
    ("htm"      , ""),
    ("html"     , ""),
    ("htpasswd" , ""),
    ("hxx"      , ""),
    ("ico"      , ""),
    ("img"      , ""),
    ("ini"      , ""),
    ("iso"      , ""),
    ("jar"      , ""),
    ("java"     , ""),
    ("jl"       , ""),
    ("jpeg"     , ""),
    ("jpg"      , ""),
    ("js"       , ""),
    ("json"     , ""),
    ("jsx"      , ""),
    ("key"      , ""),
    ("ksh"      , ""),
    ("leex"     , ""),
    ("less"     , ""),
    ("lha"      , ""),
    ("lhs"      , ""),
    ("log"      , ""),
    ("lua"      , ""),
    ("lzh"      , ""),
    ("lzma"     , ""),
    ("m4a"      , ""),
    ("m4v"      , ""),
    ("markdown" , ""),
    ("md"       , ""),
    ("mdx"      , ""),
    ("mjs"      , ""),
    ("mkv"      , ""),
    ("ml"       , "λ"),
    ("mli"      , "λ"),
    ("mov"      , ""),
    ("mp3"      , ""),
    ("mp4"      , ""),
    ("mpeg"     , ""),
    ("mpg"      , ""),
    ("msi"      , ""),
    ("mustache" , ""),
    ("nix"      , ""),
    ("o"        , ""),
    ("ogg"      , ""),
    ("pdf"      , ""),
    ("php"      , ""),
    ("pl"       , ""),
    ("pm"       , ""),
    ("png"      , ""),
    ("pp"       , ""),
    ("ppt"      , ""),
    ("pptx"     , ""),
    ("ps1"      , ""),
    ("psb"      , ""),
    ("psd"      , ""),
    ("pub"      , ""),
    ("py"       , ""),
    ("pyc"      , ""),
    ("pyd"      , ""),
    ("pyo"      , ""),
    ("r"        , "ﳒ"),
    ("rake"     , ""),
    ("rar"      , ""),
    ("rb"       , ""),
    ("rc"       , ""),
    ("rlib"     , ""),
    ("rmd"      , ""),
    ("rom"      , ""),
    ("rpm"      , ""),
    ("rproj"    , "鉶"),
    ("rs"       , ""),
    ("rss"      , ""),
    ("rtf"      , ""),
    ("s"        , ""),
    ("sass"     , ""),
    ("scala"    , ""),
    ("scss"     , ""),
    ("sh"       , ""),
    ("slim"     , ""),
    ("sln"      , ""),
    ("so"       , ""),
    ("sql"      , ""),
    ("styl"     , ""),
    ("suo"      , ""),
    ("swift"    , ""),
    ("t"        , ""),
    ("tar"      , ""),
    ("tex"      , "ﭨ"),
    ("tgz"      , ""),
    ("toml"     , ""),
    ("ts"       , ""),
    ("tsx"      , ""),
    ("twig"     , ""),
    ("vim"      , ""),
    ("vimrc"    , ""),
    ("vue"      , "﵂"),
    ("wav"      , ""),
    ("webm"     , ""),
    ("webmanifest" , ""),
    ("webp"     , ""),
    ("xbps"     , ""),
    ("xcplayground" , ""),
    ("xhtml"    , ""),
    ("xls"      , ""),
    ("xlsx"     , ""),
    ("xml"      , ""),
    ("xul"      , ""),
    ("xz"       , ""),
    ("yaml"     , ""),
    ("yml"      , ""),
    ("zip"      , ""),
    ("zsh"      , "")
    ].iter().cloned().collect()
  };
}



